### ISSUE TITLE
Product URL aliases keep disappearing

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/ubercart#336]
I haven't verified this or tracked anything down but thought I'd better add this while it was fresh in my mind. I have received a report that the automatic URL alias checkbox keeps unchecking itself somewhere along the way:

> Something I've noticed today is that the box to auto-generate a link is becoming unchecked on its own for store items.  The [certain product] just did it to me when I was updating the inventory numbers.

**Comment by bugfolder** [comment]
I'll poke into it. Can you provide a bit more detail? What report page are you looking at?

**Comment by argiepiano** [comment]
This sounds like a config issue - perhaps a misnamed key?

**Comment by bugfolder** [comment]
Yeah, that was my suspicion. Ubercart has had some problems in the past where one part adds an element to a form via `hook_form_alter()` and the setting ends up under the wrong key. (And I just learned [how to specify multiple config files within a single settings form.](https://docs.backdropcms.org/api/backdrop/core%21modules%21system%21system.module/function/system_settings_form/1))

**Comment by laryn** [comment]
As I understand it, this is the default node edit page, in the vertical tabs at the bottom, and the "Generate automatic URL alias" box gets unchecked unexpectedly. But it's not clear to me if it is being unchecked at the time of editing or at some point in between last edit and now (when it was noticed). But the report indicates it happens repeatedly over time.

EDIT: To clarify, the "report" I am talking about is an email I received from a user, not a report page on site.

**Comment by bugfolder** [comment]
Thanks for clarifying. A quick test of changing the inventory level on an existing product that has that checked doesn't affect that setting. Maybe the reporter can find a way of reproducing it?

**Comment by laryn** [comment]
Yep, I'll try to find a way to reproduce.

**Comment by laryn** [comment]
Not fully a STR yet, but it seems to be happening on newer items, which are also the most likely to be purchased, so my working theory is something in the checkout / purchase / stock process is accidentally doing this.

The site has these UC modules active:

 - Payment
 - Product Attributes
 - Reports
 - Shipping
 - Shipping Quotes
 - Ubercart
 - Stock
 - Ubercart Ajax Administration
 - U.S. Postal Service
 -  Authorize.net
 - Credit Card

And UC-related contrib modules active:

 - CSV Export
 - Out of stock notification
 - Ubercart Mini Cart Block

**Comment by amilenkov** [comment]
On an Ubercart site I built and maintained, I notice the same strange behavior - some products at some point uncheck the "Generate automatic URL alias" option and lose their URL and become just like /node/4.

To monitor this process I created a special administrative View, accessible only to me, that shows the products and their URLs.

Yesterday evening I fixed the automatic URL alias for absolutely all products, but today I find that three products have lost their URL again, I am attaching a screenshot.

And at the same time I discover that an order has been made for exactly these products today! And I have the hypothesis that this strange phenomenon happens somehow in the evaluation of adding the products to the basket or when placing an order.
![Firefox_Screenshot_2022-11-19T14-11-18 043Z](https://user-images.githubusercontent.com/14857883/202854836-9bcf65e5-5edc-4485-98b0-be7e99d9fdb0.png)

**Comment by amilenkov** [comment]
And this is a screenshot of the order after which the products lost their automatic URLs.

![Firefox_Screenshot_2022-11-19T14-17-16 429Z](https://user-images.githubusercontent.com/14857883/202855414-d6d6108a-efac-408f-8a46-d711c4ef00fc.png)

**Comment by amilenkov** [comment]
One of the products that lost its automatic URL is missing from the order - L'or Ristretto - /node/4 - SKU 0101

But I guess it was added to the basket and then removed to add a similar product - Lavazza Ristretto - SKU 0309 - which has lost the URL.

Therefore, I assume that this error occurs when adding products to the shopping cart,

The status and screenshots described above are with Ubercart version 1.x-3.13.6 installed.

**Comment by bugfolder** [comment]
Thanks for providing the additional information! Looking into this further now.

**Comment by bugfolder** [comment]
OK, I've been able to reproduce this. I went through the process of creating an order with a product that had an alias and checked the existence of the alias at each stage. Results:

* After "Add to cart" — alias still present.
* After "Checkout" — alias still present.
* AFter "Review order" — alias still present.
* After "submit order" — alias is gone.

More to come.

**Comment by argiepiano** [comment]
My guess is that the node gets updated upon submitting, based on the uc_cart_item entity, and somehow node properties like path alias get dropped. In d7 path alias were not a core feature

**Comment by bugfolder** [comment]
As usual, you beat me to it. Here's the call stack I eventually got to, which tells that same story:

![Screen Shot 2022-11-19 at 10 31 55 AM copy](https://user-images.githubusercontent.com/29214084/202866321-5124b130-deca-4cec-b315-39b7189f3f7d.jpg)

**Comment by bugfolder** [comment]
@argiepiano, in `path_delete_all_by_entity()`, we have this:

```
  $uri = $entity->uri();

  if (!empty($uri)) {
    path_delete_all_by_source($uri['path']);
    if (isset($default_uri) && $uri['path'] != $default_uri) {
      path_delete_all_by_source($default_uri);
    }
  }
```

And in `UcCartItem::uri()`, it returns the URI of the "parent node":

```
  public function uri() {
    // Since uc_order_product entities are derived from nodes, we return the uri
    // of its "parent" node.
    return array(
       'path' => 'node/' . $this->nid,
       'options' => array(),
    );
  }
```

So pathauto, seeing a valid URI, deletes the alias associated with that path—the alias of the node.

So it looks like this problem would be fixed by instead returning an empty array for `UcCartItem::uri()`. Which kinda makes sense anyhow, since this entity is never going to be viewed directly by its path. Would you agree with this course of action? (Maybe also for `UcOrderProduct`?)

**Comment by bugfolder** [comment]
...as expected, making that change fixes the disappearing alias problem, but puts lots of "Undefined index: path in path_entity_update()" into watchdog. So I guess it's not as simple as just returning an empty array.

**Comment by bugfolder** [comment]
Ah, https://docs.backdropcms.org/api/backdrop/core%21modules%21entity%21entity.class.inc/function/EntityInterface%3A%3Auri/1 says use NULL, not empty array.

**Comment by argiepiano** [comment]
@bugfolder thanks so much for looking into this. This makes a lot of sense. I kinda remember we added those lines to uri()(and had a conversation about it) last year. Changing it to NULL makes sense, as the `uc_cart_item` entity doesn't really need a uri to view/edit. It's just an auxiliary entity that holds a reference to the product node.

**Comment by argiepiano** [comment]
I haven't looked at this in detail, but see #315. I fixed this because it was producing issues with another path related function. So it's a catch 22. Maybe a bug in core?

**Comment by bugfolder** [comment]
Unfortunately, changing both to NULL still throws errors into dblog, because UcOrderProduct still has `::path` set, so `path_entity_update()` tries to do stuff.

**Comment by argiepiano** [comment]
> Unfortunately, changing both to NULL still throws errors into dblog, because UcOrderProduct still has ::path set, so path_entity_update() tries to do stuff.

Yes. I'm thinking that the way to go here is to create a unique uri for uc_cart_item entities, like `uc-cart-item/cart_item_id`, even if this is never use to display or edit

**Comment by bugfolder** [comment]
Ah yes, that was https://github.com/backdrop-contrib/ubercart/issues/315; those are the same warnings I'm seeing.

I'm not sure that it's a core bug, though. It seems like our entity, if it returns NULL for `uri()`, should not have `$entity->path` set.

**Comment by bugfolder** [comment]
Looks like `UcCartItem::uri()` returning NULL is OK. It's `UcOrderProduct::uri()` returning NULL that causes the warning, because  of this:

```
function path_entity_update(Entity $entity) {
  if (isset($entity->path)) {
    $langcode = isset($entity->langcode) ? $entity->langcode : LANGUAGE_NONE;
    $uri = $entity->uri();
    $path = $entity->path;
```

It only goes into that branch if `$entity->path` is set. If there's no URI, then logically, there ought not to be a path, but it looks like UcOrderProduct inherits that from the parent node.

**Comment by argiepiano** [comment]
> It only goes into that branch if $entity->path is set. If there's no URI, then logically, there ought not to be a path, but it looks like UcOrderProduct inherits that from the parent node.

That makes sense! So perhaps we should unset `path` somewhere when the uc_order_product entity is created based on the node.

**Comment by bugfolder** [comment]
Maybe unset `path` at the end of `UcOrderProductController::buildContent()`?

**Comment by argiepiano** [comment]
> Maybe unset path at the end of UcOrderProductController::buildContent()?

I'm not sure that would work, since buildContent is used when the entity is built for display. I'm thinking that we need to override `UcOrderProduct::__construct()` since this is where the entity "inherits" the properties from the node - when it's constructed. 

Edit:  I meant IMPLEMENT `UcOrderProduct::__construct()`

**Comment by bugfolder** [comment]
I'll try that...

**Comment by argiepiano** [comment]
This is related to another fix I did for `uc_order_product_view_multiple()`. This function creates `uc_order_product` entities (in the original Ubercart code, this function simply passed an array of nodes entities to `entity_plus_view('uc_order_product', ...`)

The problem is that, when `Entity::view()` went into core, we couldn't do that anymore. Therefore we switched to creating `uc_order_product` entities expressly. 

So, this lends credibility to the approach of implementing `UcOrderProduct:__construct` to remove `path` there when the entity is created, since this inherits this property from `node`.

**Comment by argiepiano** [comment]
@bugfolder the fix needs to be a bit more complex than what I said above.

`uc_order_save()` receives an order with an array of products. Those products are all `uc_cart_item` entities, and ALL of them have `path` properties, which they shouldn't.

So, without having done testing or a lot of thinking about this, I'm thinking that we need to be sure to remove/not set the path property BOTH for `uc_cart_item` entities, and `uc_order_product` ones.

**Comment by bugfolder** [comment]
That's what I've just been doing. Unsetting it in the constructor of UcOrderProduct seems to do the trick with respect to its warnings. But Unsetting in the constructor of UcCartItem doesn't work, because UcCartItem gets its additional properties from the node after construction.

**Comment by argiepiano** [comment]
Hi again. OK, I'm doing a bit more thinking (sorry for the barrage of responses - I'm a bit groggy after 24 hours of travel abroad). 

I think both issues (one with uc_order_product and the other with uc_cart_item) are created by the fact that we are returning the uri of a node instead of a unique uri. That causes the issues with path.

I think a better solution for both issues is to return a unique uri for each entity. This workaround will solve both problems, I believe. I suggested that above (for uc_cart_item)

**Comment by bugfolder** [comment]
Since I'm not making any headway on the UcCartItem problem (and you're the Entity Guru), I'll move on to try that!

**Comment by argiepiano** [comment]
I'm not so sure about being the Entity Guru (this issue was created by my "fix" of `uri()` !!!).

This is working for me:

In UcOrderProduct

```php 
  public function uri() {
    // Since uc_order_product entities are derived from nodes, we return the uri
    // of its "parent" node.
    return array(
      'path' => 'uc-order-product/' . $this->order_product_id,
      'options' => array(),
    );
  }
```

and in UcCartItem

```php
  /**
   * Implements EntityInterface::uri().
   */
  public function uri() {
    // Since uc_order_product entities are derived from nodes, we return the uri
    // of its "parent" node.
    return array(
       'path' => 'uc-cart-item/' . $this->cart_item_id,
       'options' => array(),
    );
  }
```

**Comment by bugfolder** [comment]
OK, this works:

* For UcOrderProduct, (a) unset `path` in the ctor, (b) return NULL for `uri()`
* For UcCartItem, use `'path' => 'node/' . $this->nid . '/uc-cart-item'` in `uri()`

Order goes through, no warnings, no removed alias.

It still kind of bugs me to create a path that doesn't exist as a workaround, though.

**Comment by argiepiano** [comment]
> It still kind of bugs me to create a path that doesn't exist as a workaround, though.

Exactly. Me too.

If we implemented my solution above, we _could_ create paths to see both entities, even though they will never be seen....

**Comment by bugfolder** [comment]
Do you know where in the code UcCartItem acquires its fields from the node product?

**Comment by bugfolder** [comment]
Since the documentation for EntityInterface explicitly states that returning NULL for `uri()` is a valid behavior, that seems to me to be preferred, and for UcOrderProduct, it even works (it appears). So for UcOrderProduct, at least, I'd like to suggest we use that working solution.

For UcCartItem, even though the fictitious path works, I'd still like to do a little more looking at alternatives; if there's a way to clear `path` at the right place, then NULL `uri()` should work for that, too.

**Comment by argiepiano** [comment]
> For UcCartItem, even though the fictitious path works, I'd still like to do a little more looking at alternatives; if there's a way to clear path at the right place, then NULL uri() should work for that, too.

That makes sense to me. I'm about to leave for a couple of hours and can take a closer look later (or perhaps you'll have found a fix by then). I'm in Argentina time right now (UTC-3). More later!

**Comment by bugfolder** [comment]
OK, I've filed a PR that seems to work on my local version (of a real production site). It returns NULL for both URIs, and strategically unsets `path` so that pathauto doesn't try to modify aliases. So no lost aliases, and no warnings in watchdog.

I did run across one weird thing. During the course of checkout, `uc_order_product_save($order_id, $product)` gets called a couple of times, and the passed `$product` is a `UcCartItem`. But it's passed to `UcOrderProductController` for saving (i.e., `return entity_get_controller('uc_order_product')->save($product)`). 

I would have thought that in that case, one should use `entity_get_controller('uc_cart_item')->save($product)` when it's a `UcCartItem`, but no, that emits smoke and flames. So I just added a comment on the call for posterity (which you will see in the PR).

**Comment by bugfolder** [comment]
Ah well, we're not ready yet; automated Ubercart tests are now failing path-related stuff. I'll look further into this tomorrow.

**Comment by bugfolder** [comment]
Well, that wasn't too bad. One more clearance of `UcCartItem::path` and all tests are passing now.

**Comment by argiepiano** [comment]
@bugfolder thanks for all the sleuthing and the PR! I've looked at this pretty closely today. The approach seems right to me: return NULL for uri() methods, unsetting `path` in the constructor.

The only one that seems misplaced to me is the `unset($product->path)` you placed in `UcOrderProductController::save()`.  Notice that `save()` actually doesn't save `path` in the DB, as there is no column to hold it in the table `uc_order_products`.  This `unset`  is working only because the $product object remains active after the `save` call, and this $product is later used when building the checkout page etc.   

So, a better approach is to "nip it from the bud," that is, remove the `path` property BEFORE we get to the `save` call.  I found the exact location where the $product gets added all the `node` properties: it's done in `uc_order_product_revive()` in the loop that starts in [line 1182](https://github.com/backdrop-contrib/ubercart/blob/1375752b61b8efd05a25481fd44d647dc1fcb1cc/uc_order/uc_order.module#L1180).

So, instead of unsetting path in the save method, in my opinion it's best to unset right after it's added, in that loop mentioned above. This would look like:

```php
foreach ($products as &$product) {
    if (!empty($nodes[$product->nid]) && (!$published || $nodes[$product->nid]->status == NODE_PUBLISHED)) {
      foreach ($nodes[$product->nid] as $key => $value) {
        if (!isset($product->$key)) {
          $product->$key = $value;
        }
      }
      unset($product->path);
      // Order products are always variants.
      $product->variant = TRUE;
    }
    else {
      $return = FALSE;
    }
  }
```

(Notice the `unset` above). After this you can remove the unset from the save method. 

Give it a try and let me know if this doesn't make sense.

**Comment by argiepiano** [comment]
Actually, doing what I suggested above still throws a notice `Notice: Trying to access array offset on value of type null in path_entity_update() (line 494 of`  so... no joy. 

My comment about the unset in the save method is still relevant, I think - I'd like to try to find why the entity received by `UcOrderProductController::save()` contains the `path` property. Unfortunately I don't think I can get to this today... perhaps we can wait until tomorrow to try to fix this?

**Comment by bugfolder** [comment]
> perhaps we can wait until tomorrow to try to fix this?

Sure.

 I definitely agree with the "bud-nipping" approach. `UcOrderProductController::save()` was the best I could do that worked, but it bugged me that the fix wasn't logically something that should happen during saving; that was just the place I found that could properly create the needed side effect. So the right place earlier in the logic would be better.

**Comment by argiepiano** [comment]
OK, I found it. 

These are the places where we should `unset` the `path`:

- Constructors for `UcCartItem` and `UcOrderProduct` (I think you only had it in `UcOrderProduct`)
- `UcCartItemController::attachLoad()` (this is the one missing in my suggestion above. It's here where the product (at this point a UcCartItem) acquires all the node properties). See code for this method below.
-  `uc_order_product_revive()` as explained in my comment above

We can safely remove the unset from the `save` method.

UcCartItemController::attachLoad()

```php
  public function attachLoad(&$items, $revision_id = FALSE) {
    foreach ($items as &$item) {
      $product = uc_product_load_variant($item->nid, $item->data);
      if ($product) {
        // Merge in fields from the product.
        foreach ($product as $key => $value) {
          $item->$key = $value;
        }
        // UcCartItem should not have a path (inherited from the node) so that
        // path module doesn't try to update the node's alias.
        unset($item->path);
      }
      $item->module = $item->data['module'];
    }
    parent::attachLoad($items, $revision_id);
  }
```

**Comment by bugfolder** [comment]
Nope, sorry, that doesn't fix things.

I had previously tried unsetting in the ctor for `UcCartItem`, but that didn't accomplish anything because in most cases the product information came later, after construction. So that's why I left it out.

(I'd also tried unsetting in attachLoad(), but that didn't solve the problem during checkout.)

But in any event, I've done all of the things in your bullet points above:

* `unset($this->path)` in both ctors
* `unset($item->path)` in `UcCartItemController::attachLoad()`
* `unset($product->path)` in `uc_order_product_revive()`
* Remove the unsetting from `UcOrderProductController::save()`

And I'm seeing warnings again. Restore the `save()` unset and the warnings are fixed.

Incidentally, I get rapid feedback on whether something works by editing `path_entity_update()` like this:

```
function path_entity_update(Entity $entity) {
  if (isset($entity->path)) {
    $langcode = isset($entity->langcode) ? $entity->langcode : LANGUAGE_NONE;
    $uri = $entity->uri();

if (is_null($uri) && isset($entity->path)) {
dpm($entity,'mismatched $uri and $path');
}

    $path = $entity->path;
    $path['source'] = $uri['path'];
...
```

Then when I go to check out, as soon as I check the "My billing information is the same as my delivery information" checkbox, the error message appears via the ajax.

**Comment by argiepiano** [comment]
Have you tried removing all products from cart and starting a brand new order after all these fixes?

**Comment by bugfolder** [comment]
> Have you tried removing all products from cart and starting a brand new order after all these fixes?

Yes.

**Comment by bugfolder** [comment]
It looks like if I put the unset in `uc_order_product_save()`, I can eliminate both of the modifications to `::save()` and get no errors during checkout. Of course, it's still doing the tweaking during saving, but I note that `uc_order_product_save()` does other tweaking to `$product`, so that doesn't feel quite as contrived. Dunno yet if that fixes all the automated tests; I'll check that tomorrow.

**Comment by argiepiano** [comment]
@bugfolder I've done some more testing of my suggestions above, and it's working for me. I don't get any warnings anymore. I've tried with a registered user and anonymous, and with a Credit Card test gateway.

To make it easier for you to test this, instead of including a bullet list of changes, I've pushed a new PR with the changes I made. I can close it later if you prefer to use your own PR with the appropriate changes. 

Can you please test again, but this time start with a Vanilla install of Backdrop and Ubercart? Either patch the 1.x-3.x code of Ubercart with my diff file, or download my new branch of Ubercart from where I'm making this PR.

Thanks!

**Comment by argiepiano** [comment]
I'm getting a test failure in my PR. I'll check that in about 1 hour

**Comment by bugfolder** [comment]
Well, I downloaded your branch and replaced the ubercart module with it in my local version of my live site. And i'm seeing the error during checkout (starting checkout entirely from scratch: empty cart, add product to cart, then checkout.)

Yes, it's definitely not a "plain vanilla" UC installation, but our fix will need to work on existing sites! (At least, on mine 😉.)

If I simply add `unset($product->path);` to function `uc_order_product_save()` to your branch, that makes the errors go away (at least during checkout).

As I noted above, in that `uc_order_product_save()` call, the problematic `$product` during checkout is a `UcCartItem`, but we're calling `UcOrderProductController::save()` on it, which seems weird.

**Comment by argiepiano** [comment]
Wow, that's really strange. Can you tell me exactly when you are seeing the error? In my case, before the patch, it happens at the last step of the order, when I click cancel, and Backdrop sends me back to the Checkout page. With the patch I don't see this.

Yes, unsetting path in the save function will also work. The problem is thrown in `path_entity_update()` a hook implementation that is invoked every time Backdrop saves an entity (e.g. the product). So it makes sense that removing `path` in the function that saves the entity will avoid the issue. As discussed above, ideally we would catch this when the entity is first constructed and the properties are set.

It's very difficult for me to pinpoint the exact problem now that my patch is avoiding the original warning. I can't reproduce the problem. So, if you want to go ahead with this less desirable approach, go for it. Or we can try continuing to dig. As I'm abroad right now visiting family, I am not having as much time to troubleshoot.

**Comment by argiepiano** [comment]
One other thought: it may be possible you have another Ubercart submodule enabled, which I don't have. That submodule may be constructing the product entity separately. 

Can you tell me what other UC submodules you have enabled?

**Comment by argiepiano** [comment]
@bugfolder thinking more about this. There is nothing wrong with unsetting the path in the save function. In fact this may also save us some troubles with contrib modules that modify products in any way by using data stored in the node. 

So, let's go for that instead of the other approach.

> As I noted above, in that uc_order_product_save() call, the problematic $product during checkout is a UcCartItem, but we're calling UcOrderProductController::save() on it, which seems weird.

Yes, I noticed this some time ago when I was working on fixing tests etc. UC's approach to the product  / cart item entities is definitely not great. They are similar entities that contain similar information, and originally (before Entity API) they were stdClass objects that were more easily interchangeable. AFAICT uc_cart_item is used to temporarily store products that are in the cart, and uc_order_product is used to store it when it's already part of an order. The issue happens when you cancel the order checkout: the uc_cart_item entities are recreated based on the uc_order_product entities.

In Drupal Commerce, all this mess of having two "holding" entities (cart and order) was avoided by skipping this "cart" limbo". Instead Commerce creates an order as soon as you put a product in your cart. That order has a status of "In shopping cart".  In UC, the order is only created in the last steps of the Checkout, and continues to exists if you cancel and go back.

**Comment by bugfolder** [comment]
> Can you tell me exactly when you are seeing the error?

Yes. It happens right when I toggle the "My billing address is the same as my shipping address" checkbox (either toggle on or off). I've put a conditional `dpm()` in `path_entity_update()` that checks for the problem, so I see the error appear in the AJAX response (so I don't have to keep refreshing watchdog). So it was happening even without cancelling the checkout (TBH, I never got to that point in my testing!).

And I do definitely have lots of other UC submodules enabled, both contrib and custom. It may well be that one of them is updating the order (for example, I have a modified version of the `uc_usps` module that fully packages the products before doing the USPS rate lookup, since the rates are package-dependent). So it could well be that one of them is updating the order from products outside of the channels you've already got covered.

So that suggests that adding the unset to `uc_order_product_save()` is a good defensive move on general principles—in addition to the "nipping it in the bud" unsets that you've put in. Since existing installations may well be doing something similar.

> Instead Commerce creates an order as soon as you put a product in your cart. 

That makes way more sense. (Though not enough sense to induce me to try to port Commerce!)

**Comment by argiepiano** [comment]
Sounds good. I'll close my PR now

**Comment by bugfolder** [comment]
I've incorporated your changes into my PR and added the `uc_order_product_save()` unsetting. All automated tests have passed, and my local testing also had no warning messages in watchdog. So I think we're good to go!

This seems critical enough that it warrants merging (and I'll merge the other pending PRs, too) and a new bugfix release ASAP. Agreed?

**Comment by argiepiano** [comment]
Agreed! Thanks, @bugfolder

**Comment by amilenkov** [comment]
Thanks a lot friends! I purposely delayed this post waiting to install new Ubercart version and test on two sites with Backdrop and Ubercart while also waiting for real customer orders. Everything seems to be working perfectly and I don't see any problems with the URLs anymore.

I have watched your correspondence with great interest in trying to solve the problem, and I admire your tenacity and dedication to the open source cause - i could see the open source philosophy working in practice.

And since my specialty isn't even graphic design and site development, but philosophy (I'm a former assistant professor of history and philosophy of science at Sofia University) - I can tell, you guys aren't just writing code, you're writing history!
